---
title: "Ценови стратегии"
author: "Виктор Аврамов"
format: revealjs
---

## Ценова дилема


| Фирма 1/Фирма2| цена = 3  | цена = 2,50 | 
|---------------|:----------|------------:|
| цена = 3      | 100,100   |   0, 150    |      
| цена = 2,50   | 150,0     |   75,75     |     


: Ценова дилема

## Критики/ограничения

1. Ценовата дилема се случва само веднъж.
2. Фирмените разходи са еднакви.
3. Няма ограничения на капацитета.
4. Продуктите не са диференцирани.
5. Купувачите и продавачите имат симетрична и пълна информация.

## Въпроси

1. Мениджърите фокусират ли се само върху краткосрочните ползи? Това е възможно по две причини: 

- ако имат краткосрочни цели (като месечни или тримесечни резултати);
- ако се сключват малко на брой сделки.

## Въпроси

2. Разходите на фирмите еднакви ли са?

3. Има ли производствен свръхкапацитет?

4. Има ли продуктова диференциация?

5. Каква е степента на пазарната прозрачност?

## Дискусия

- Мините за диаманти в Конго
- Продуктова диференциация

## В отговор на продуктовата диференциация

Купувачът може:

- да каже 'не, благодаря'; така той се отказва от функция на продукта, на което държи, за да получи по-ниска цена;
- да поиска същата функция от друг доставчик;
- да поиска предоговаряне на цената.

## В отговор на продуктовата диференциация

::: {.incremental}
Защо предоговарянето на цената е възможно?

Защото продавачът печели ако обвърже всички качества в един продукт. Ако се откаже от качество, което само той предлага, губи конкурентното си предимство, предлагайки това, което всички останали предлагат.

:::

## Един извод

Достатъчен е малък брой доставчици за да може потребителите да извлекат ползи от конкуренцията. Ако има доминиращ доставчик, който предлага повече стойност, разумните купувачи го избират за повече, но не всичките си нужди, за да държат останалите доставчици наоколо. Това е достатъчно за наличието на конкурентен натиск върху основния доставчик.

## Повторения на ценовата дилема

Възможни стратегии при многобройни итерации на играта:

1. Винаги избирай по-ниската цена.
2. Избери по-високата цена в първия рунд на играта. Всеки следващ рунд, в който опонентът избере високата цена, избери високата цена. Ако опонентът избере ниската цена веднъж, избирай ниската цена до края на играта. Това е известно като **the grim trigger**.

## Повторения на ценовата дилема - продължение

3. Избери високата цена в първия рунд на играта. Всеки следващ рунд избирай това, което опонентът ти е избрал в предишния.  Това е известно като **tit for tat**.

Какво е привлекателното в стратегията **tit for tat**?

## Забранени споразумения и агресивно ценообразуване (predatory pricing)

КЗК: 'Законът за защита на конкуренцията (ЗЗК) определя картелите като споразумения и/или съгласувани практики между две или повече предприятия - конкуренти на съответния пазар, насочени към ограничаване на конкуренцията чрез определяне на цени или ценови условия за покупка или продажба, разпределяне на квоти за производство или продажби или разпределяне на пазари, включително при манипулиране на публични търгове или конкурси...'

## Забранени споразумения и агресивно ценообразуване (predatory pricing)

Тези споразумения заменят конкуренцията с пазарене в затворени хотелски стаи. Участниците в тези преговори се договарят как да разделят печалбите от споразумението помежду си. В дългосрочен план това означава наблюдение на цените и количествата между тях.

## Забранени споразумения и агресивно ценообразуване (predatory pricing)

Ако фирмите имат ограничен капитал, намаляването на цената може да изведе от пазара тези, които имат по-високи разходи. При две фирми, останалият се превръща в монополист. Ако има достатъчно време, той може да възстанови разходите, направени за агресивнно ниските цени.

**The winner's curse.**

## Капацитет


| Фирма 1/Фирма2| цена = 3  | цена = 2,50 | 
|---------------|:----------|------------:|
| цена = 3      | 40,40     |   40, 30    |      
| цена = 2,50   | 30,40     |   30, 30    |     


: Ценова дилема: всяка фирма има капацитет 20, а общото търсене е равно на 100 единици.


## Програми за лоялност

- атрактивни за нови клиенти;
- намалява стимулите за преминаване към друг доставчик;
- може да увеличава повеблението на същия или други продукти;
- увеличава продуктовара диференциация като създава емоциално свързване;
- събира информация за клиентите.

## Програмите за лоялност може да не са печеливши

1. Те са скъпи (Gigliano, J., M. Georgiadis, D. Pleasance, and S. Whaley. “The price of loyalty” McKinsey Quarterly, No. 4, 68–77, 2000)
2. След като правилата са създадени, вече е трудно са се променят.

## Допълващи продукти

Дайте примери за продукти, които могат да се третират като допълващи и това да е свързано с ценовата стратегия на фирмата.




